### ISSUE TITLE
Enum global questions

### ISSUE THREAD

**Issue by Allen-B1** [rbuckton/proposal-enum#7]
I feel that many functions of the `Enum` global are unnecessary

`Enum.has(E, key)` -> `key in E`
`Enum.hasValue(E, val)` -> `val of E`
`Enum.keys()`, `Enum.values()` , `Enum.entries()` -> `Object.keys()`, `Object.values()`, `Object.entries()`
`Enum.parse(E, value)` -> `E[value]`

**Comment by ljharb** [comment]
in checks the prototype chain; has is appropriately explicit.

**Comment by Allen-B1** [comment]
oh
